I got a bug in counting in `part2.py`, so I made a copy (`newpart2.py`) to fix it, so use that one instead.
